services:
  db:
    image: postgres:16-alpine
    container_name: notes_app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_app_gcloud_dev
    ports:
      - "5433:5432"
    volumes:
      - notes_app_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_app_gcloud_dev"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  notes_app_pg_data:
